apiVersion: v1
kind: Namespace
metadata:
  name: sns

---

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  redis_password:  LSBmb29iYXJlZAo= 

---

apiVersion: v1
kind: Secret
metadata:
  name: ingress-cert
  namespace: sns
type: "kubernetes.io/tls"
data:
  tls.crt: ""
  tls.key: ""
  